In [4]:
import sys
sys.path.append("../src")

from preprocessing import preprocess_dataframe, split_data, combine_comment_rule
import pandas as pd

In [5]:
%run 01_eda.ipynb

In [3]:
train_df.head()

,row_id,body,rule,subreddit,positive_example_1,positive_example_2,negative_example_1,negative_example_2,rule_violation
0,0,Banks don't want you to know this! Click here ...,"No Advertising: Spam, referral links, unsolici...",Futurology,If you could tell your younger self something ...,hunt for lady for jack off in neighbourhood ht...,Watch Golden Globe Awards 2017 Live Online in ...,"DOUBLE CEE x BANDS EPPS - ""BIRDS""\n\nDOWNLOAD/...",0
1,1,SD Stream [ ENG Link 1] (http://www.sportsstre...,"No Advertising: Spam, referral links, unsolici...",soccerstreams,[I wanna kiss you all over! Stunning!](http://...,LOLGA.COM is One of the First Professional Onl...,#Rapper \n🚨Straight Outta Cross Keys SC 🚨YouTu...,[15 Amazing Hidden Features Of Google Search Y...,0
2,2,Lol. Try appealing the ban and say you won't d...,No legal advice: Do not offer or request legal...,pcmasterrace,Don't break up with him or call the cops. If ...,It'll be dismissed: https://en.wikipedia.org/w...,Where is there a site that still works where y...,Because this statement of his is true. It isn'...,1
3,3,she will come your home open her legs with an...,"No Advertising: Spam, referral links, unsolici...",sex,Selling Tyrande codes for 3€ to paypal. PM. \n...,tight pussy watch for your cock get her at thi...,NSFW(obviously) http://spankbang.com/iy3u/vide...,Good News ::Download WhatsApp 2.16.230 APK for...,1
4,4,code free tyrande --->>> [Imgur](http://i.imgu...,"No Advertising: Spam, referral links, unsolici...",hearthstone,wow!! amazing reminds me of the old days.Well...,seek for lady for sex in around http://p77.pl/...,must be watch movie https://sites.google.com/s...,We're streaming Pokemon Veitnamese Crystal RIG...,1

In [6]:
# Clean all the text-based columns in the train dataset

columns_to_clean = ["body", "rule", "positive_example_1", "positive_example_2", "negative_example_1", "negative_example_2"]
train_df_clean = preprocess_dataframe(train_df, columns_to_clean, label_column="rule_violation")
train_df_clean.head()

,row_id,body,rule,subreddit,positive_example_1,positive_example_2,negative_example_1,negative_example_2,rule_violation
0,0,banks don't want you to know this click here t...,no advertising spam referral links unsolicited...,Futurology,if you could tell your younger self something ...,hunt for lady for jack off in neighbourhood,watch golden globe awards 2017 live online in ...,double cee x bands epps birds downloadstream,0
1,1,sd stream eng link 1,no advertising spam referral links unsolicited...,soccerstreams,i wanna kiss you all over stunning,lolgacom is one of the first professional onli...,rapper straight outta cross keys sc youtube se...,15 amazing hidden features of google search yo...,0
2,2,lol try appealing the ban and say you won't do...,no legal advice do not offer or request legal ...,pcmasterrace,don't break up with him or call the cops if yo...,it'll be dismissed the first amendment law her...,where is there a site that still works where y...,because this statement of his is true it isn't...,1
3,3,she will come your home open her legs with and...,no advertising spam referral links unsolicited...,sex,selling tyrande codes for 3 to paypal pm,tight pussy watch for your cock get her at thi...,nsfwobviously,good news download whatsapp 216230 apk for and...,1
4,4,code free tyrande imgur for you and your frien...,no advertising spam referral links unsolicited...,hearthstone,wow amazing reminds me of the old dayswell do ...,seek for lady for sex in around,must be watch movie,we're streaming pokemon veitnamese crystal rig...,1

In [8]:
train_df_clean.count()

row_id                2029
body                  2029
rule                  2029
subreddit             2029
positive_example_1    2029
positive_example_2    2029
negative_example_1    2029
negative_example_2    2029
rule_violation        2029
dtype: int64

In [9]:
train_df_clean.describe()

            row_id  rule_violation
count  2029.000000     2029.000000
mean   1014.000000        0.508132
std     585.866168        0.500057
min       0.000000        0.000000
25%     507.000000        0.000000
50%    1014.000000        1.000000
75%    1521.000000        1.000000
max    2028.000000        1.000000

In [8]:
train_df_clean = combine_comment_rule(train_df_clean, "body", "rule", "combined_text")

In [9]:
train_df_clean.head()

,row_id,body,rule,subreddit,positive_example_1,positive_example_2,negative_example_1,negative_example_2,rule_violation,combined_text
0,0,banks don't want you to know this click here t...,no advertising spam referral links unsolicited...,Futurology,if you could tell your younger self something ...,hunt for lady for jack off in neighbourhood,watch golden globe awards 2017 live online in ...,double cee x bands epps birds downloadstream,0,banks don't want you to know this click here t...
1,1,sd stream eng link 1,no advertising spam referral links unsolicited...,soccerstreams,i wanna kiss you all over stunning,lolgacom is one of the first professional onli...,rapper straight outta cross keys sc youtube se...,15 amazing hidden features of google search yo...,0,sd stream eng link 1 [SEP] no advertising spam...
2,2,lol try appealing the ban and say you won't do...,no legal advice do not offer or request legal ...,pcmasterrace,don't break up with him or call the cops if yo...,it'll be dismissed the first amendment law her...,where is there a site that still works where y...,because this statement of his is true it isn't...,1,lol try appealing the ban and say you won't do...
3,3,she will come your home open her legs with and...,no advertising spam referral links unsolicited...,sex,selling tyrande codes for 3 to paypal pm,tight pussy watch for your cock get her at thi...,nsfwobviously,good news download whatsapp 216230 apk for and...,1,she will come your home open her legs with and...
4,4,code free tyrande imgur for you and your frien...,no advertising spam referral links unsolicited...,hearthstone,wow amazing reminds me of the old dayswell do ...,seek for lady for sex in around,must be watch movie,we're streaming pokemon veitnamese crystal rig...,1,code free tyrande imgur for you and your frien...

In [10]:
# Train and validation split

X_train, X_val, y_train, y_val = split_data(train_df_clean, label_column='rule_violation')

print(f"Train size: {len(X_train)}")
print(f"Validation size: {len(X_val)}")

Train size: 1623
Validation size: 406

In [11]:
train_df_clean.to_csv("../data/processed/train_cleaned.csv", index=False)